Repository Ji-Hyeon212/wagglewaggle, pull requests merged in 2024-08, with the labels that each got.

#7 숙소 등록 단계별 컴포넌트 생성
  src/app/components/register/Step1.tsx
  src/app/components/register/Step2.tsx
  src/app/components/register/Step3.tsx
  src/app/components/register/Step4.tsx
  src/app/register/page.tsx
  src/app/reservation/page.tsx
  src/app/types/types.ts
Labels: feature, 프론트엔드, 김준서

#10 #6 상세페이지 UI 구현
  public/images/detail/alarmicon.svg
  public/images/detail/bedicon.svg
  public/images/detail/calendaricon.svg
  public/images/detail/description.svg
  public/images/detail/granpahouse.svg
  public/images/detail/haman.png
  public/images/detail/phoneicon.svg
  public/images/detail/pin.svg
  public/images/detail/rate.svg
  public/images/detail/usericon.svg
  src/app/detail/page.tsx
Labels: design

#14 숙소 등록 단계별 페이지 구현완료
  src/app/register/page.tsx
  src/app/types/types.ts
  src/components/register/Step5.tsx
Labels: feature, 프론트엔드, 김준서

#15 결제 완료 기능 구현
  public/images/reservation/completeReservation.png
  src/app/complete-reservation/page.tsx
  src/app/reservation/page.tsx
Labels: feature
